configure: Check for VapourSynth headers separately

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -90,7 +90,6 @@ LIBNAME=""
 CXXFLAGS="-std=c++11 -Wall -I. -I$SRCDIR/include"
 LDFLAGS=""
 SOFLAGS="-shared"
-DEPLIBS=""
 
 TARGET="-msse2"
 
@@ -189,14 +188,16 @@ PKGCONFIGBIN="pkg-config"
 test -n "$(which ${CROSS}${PKGCONFIGBIN} 2> /dev/null)" && \
     PKGCONFIGBIN=${CROSS}${PKGCONFIGBIN}
 
-if $PKGCONFIGBIN --exists $DEPLIBS 2> /dev/null; then
-    LIBS="$($PKGCONFIGBIN --libs $DEPLIBS)"
-    CXXFLAGS="$CXXFLAGS $($PKGCONFIGBIN --cflags $DEPLIBS)"
+
+log_echo "checking for vapoursynth headers..."
+if $PKGCONFIGBIN --exists vapoursynth 2> /dev/null; then
+    CXXFLAGS="$CXXFLAGS $($PKGCONFIGBIN --cflags vapoursynth)"
 else
-    for lib in $DEPLIBS; do
-        LIBS="$LIBS -l${lib#lib}"
-    done
-    log_echo "warning: pkg-config or pc files not found, lib detection may be inaccurate."
+    log_echo "warning: pkg-config or pc files not found, header detection may be inaccurate."
+fi
+if ! cc_check "$CXXFLAGS" "$LDFLAGS $LIBS $XLIBS" "VapourSynth.h" "getVapourSynthAPI;" ; then
+    log_echo "error: vapoursynth checking failed."
+    error_exit "VapourSynth.h might not be installed."
 fi
 
 LDFLAGS="$SOFLAGS $LDFLAGS"
