Normalize configure script

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -4,6 +4,8 @@
 #  configure script for VapourSynth-TCanny
 #----------------------------------------------------------------------------
 
+## This script was modified based on d2vsource/configure.
+
 # -- help -------------------------------------------------------------------
 if test x"$1" = x"-h" -o x"$1" = x"--help" ; then
 cat << EOF
@@ -90,8 +92,6 @@ LIBNAME=""
 CXXFLAGS="-std=c++11 -Wall -I. -I$SRCDIR/include"
 LDFLAGS=""
 SOFLAGS="-shared"
-DEPLIBS=""
-
 TARGET="-msse2"
 
 # -- options ----------------------------------------------------------------
@@ -189,18 +189,20 @@ PKGCONFIGBIN="pkg-config"
 test -n "$(which ${CROSS}${PKGCONFIGBIN} 2> /dev/null)" && \
     PKGCONFIGBIN=${CROSS}${PKGCONFIGBIN}
 
-if $PKGCONFIGBIN --exists $DEPLIBS 2> /dev/null; then
-    LIBS="$($PKGCONFIGBIN --libs $DEPLIBS)"
-    CXXFLAGS="$CXXFLAGS $($PKGCONFIGBIN --cflags $DEPLIBS)"
+log_echo "checking for vapoursynth headers..."
+if $PKGCONFIGBIN --exists vapoursynth 2> /dev/null; then
+    VSCFLAGS="$($PKGCONFIGBIN --cflags vapoursynth)"
 else
-    for lib in $DEPLIBS; do
-        LIBS="$LIBS -l${lib#lib}"
-    done
-    log_echo "warning: pkg-config or pc files not found, lib detection may be inaccurate."
+    log_echo "warning: pkg-config or pc files not found, header detection may be inaccurate."
+fi
+if ! cc_check "$CXXFLAGS $VSCFLAGS" "$LDFLAGS $LIBS $XLIBS" "VapourSynth.h" "getVapourSynthAPI;" ; then
+    log_echo "error: vapoursynth checking failed."
+    error_exit "VapourSynth.h might not be installed."
 fi
 
 LDFLAGS="$SOFLAGS $LDFLAGS"
 LIBS="$LIBS $XLIBS"
+CXXFLAGS="$CXXFLAGS $VSCFLAGS"
 
 
 cat >> config.mak << EOF
